version: '3'

services:
  straight: 
    build: ./straight
    container_name: straight
    ports:
      - "5000:5000"

  curves: 
    build: ./curves
    container_name: curves
    ports:
      - "5005:5005"
    volumes:
      ./curves:/app

  polygons: 
    build: ./polygons
    container_name: polygons
    ports:
      - "5010:5010"
    volumes:
      ./polygons:/app

  # interface: 
  #   build: ./
  #   container_name: interface
  #   ports:
  #     - "5015:5015"